"use client";

import { FileDown, FileText } from "lucide-react";
import { Order } from "@/types/order";

interface ExportButtonsProps {
  orders: Order[];
  branchId: string;
  disabled?: boolean;
}

function exportToCSV(orders: Order[], branchId: string) {
  const headers = ["Order ID", "Status", "Total Amount", "Date", "Branch ID"];
  const rows = orders.map((o) => [
    "#" + o.id,
    o.status,
    "$" + Number(o.totalAmount).toFixed(2),
    new Date(o.createdAt).toLocaleString(),
    "Branch #" + o.branchId,
  ]);

  const csvContent = [headers, ...rows]
    .map((row) => row.map((cell) => '"' + cell + '"').join(","))
    .join("\n");

  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = "haji-cafe-branch-" + branchId + "-orders.csv";
  link.click();
  URL.revokeObjectURL(url);
}

async function exportToPDF(orders: Order[], branchId: string) {
  const { default: jsPDF } = await import("jspdf");
  const doc = new jsPDF();

  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Haji Cafe - Branch Orders Report", 14, 22);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text("Branch #" + branchId, 14, 30);
  doc.text("Exported: " + new Date().toLocaleString(), 14, 36);
  doc.text("Total Orders: " + orders.length, 14, 42);

  doc.setDrawColor(200);
  doc.line(14, 46, 196, 46);

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(80);
  doc.text("ORDER ID", 14, 54);
  doc.text("STATUS", 50, 54);
  doc.text("TOTAL", 110, 54);
  doc.text("DATE", 145, 54);

  doc.setDrawColor(220);
  doc.line(14, 56, 196, 56);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(40);
  let y = 63;

  for (const o of orders) {
    if (y > 272) {
      doc.addPage();
      y = 20;
    }

    doc.text("#" + o.id, 14, y);
    doc.text(o.status.replace("_", " "), 50, y);
    doc.text("$" + Number(o.totalAmount).toFixed(2), 110, y);
    doc.text(new Date(o.createdAt).toLocaleDateString(), 145, y);

    doc.setDrawColor(240);
    doc.line(14, y + 2, 196, y + 2);
    y += 8;
  }

  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by Haji Cafe Management System", 14, 285);
  doc.save("haji-cafe-branch-" + branchId + "-orders.pdf");
}

export function ExportButtons({ orders, branchId, disabled }: ExportButtonsProps) {
  const isDisabled = disabled || orders.length === 0;

  return (
    <div style={{ display: "flex", gap: 8 }}>
      <button
        className="btn btn-ghost btn-sm"
        disabled={isDisabled}
        onClick={() => exportToCSV(orders, branchId)}
        title={orders.length === 0 ? "No orders to export" : "Export as CSV"}
        style={{ display: "flex", alignItems: "center", gap: 6 }}
      >
        <FileDown size={14} />
        CSV
      </button>

      <button
        className="btn btn-ghost btn-sm"
        disabled={isDisabled}
        onClick={() => exportToPDF(orders, branchId)}
        title={orders.length === 0 ? "No orders to export" : "Export as PDF"}
        style={{ display: "flex", alignItems: "center", gap: 6 }}
      >
        <FileText size={14} />
        PDF
      </button>
    </div>
  );
}